[package]
name = "cve-2019-16880"
version = "0.1.0"
# edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
generic-array = "=0.12.0"
linea = "=0.9.4"
typenum = "=1.10.0"

[profile.dev]
opt-level = 0
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = false
