[toolchain]

channel = "nightly-2019-09-13"
# channel = "nightly-2021-03-23"
# channel = "nightly-2022-05-18"
# channel = "nightly-2022-06-27"
# channel = "nightly-2022-07-09"
# channel = "nightly-2022-08-08"