[toolchain]

# channel = "nightly-2019-09-13"
# channel = "nightly-2021-02-03"
# channel = "nightly-2021-04-15"
# channel = "nightly-2022-02-09"
# channel = "nightly-2022-03-22"
# channel = "nightly-2021-03-23"
# channel = "nightly-2022-05-18"
# channel = "nightly-2022-06-27"
# channel = "nightly-2022-07-09"
channel = "nightly-2022-08-08"